# Simulation parameters
ref_len = config["reference_length"]
query_len = config["query_length"]
matches = config["match_count"]

# local match lengths 
min_len = config["min_match_len"]
max_len = config["max_match_len"]

# DREAM-Stellar parameters
seg_overlap = min_len
bin_nr = config["bin_nr"]
bin_list = list(range(bin_nr))
error_rates = config["error_rates"]

# Evaluation parameters
min_overlap = config["min_truth_overlap"] #how much stellar match has to overlap the ground truth

workdir: config['workdir']


rule make_all:
	input:
		expand("evaluate/stellar_e{er}_diff.gff", er = error_rates),
		expand("evaluate/dream_stellar_e{er}_diff.gff", er = error_rates)
	shell:
		"echo 'Done'"

include: "rules/simulate.smk"
include: "rules/stellar.smk"
include: "rules/evaluate.smk"

