name: CI on Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  CMAKE_VERSION: 3.16.9
  SEQAN3_NO_VERSION_CHECK: 1
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Coverage gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Coverage
            cxx_flags: "-std=c++23"

    steps:
      - name: Set repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # How many commits do we need to fetch to also fetch the branch point?
      - name: Get fetch depth
        id: fetch_depth
        run: echo "depth=$(( ${{ github.event.pull_request.commits }} + 2 ))" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPOSITORY_NAME }}
          fetch-depth: ${{ steps.fetch_depth.outputs.depth }}
          submodules: recursive

      - name: Add package source
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: |
          conda install --yes --override-channels --channel conda-forge ccache
          sudo ln -s $CONDA/bin/ccache /usr/bin/ccache

      - name: Install compiler ${{ matrix.cxx }}
        run: sudo apt-get install --yes ${{ matrix.cxx }}

      - name: Install gcovr
        env:
          CC: ${{ matrix.cc }}
        run: |
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/${CC/gcc/gcov} 100
          pip install gcovr==5.0

      - name: Load ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../${{ env.REPOSITORY_NAME }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                              -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }} -Wno-interference-size"
          make -j2 gtest_build

      - name: Build application
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 525M
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
        run: |
          ccache -z
          cd build
          make -k -j2
          ccache -sv

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 525M
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
        run: |
          ccache -z
          cd build
          make -k -j2 api_test cli_test
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure

      - name: Generate coverage report
        run: |
          gcovr --gcov-executable ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/gcov.sh \
                --root ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}/test/coverage \
                ${{ github.workspace }}/build \
                --filter ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}/include \
                --filter ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}/src \
                --exclude-lines-by-pattern '^\s*$' \
                --exclude-lines-by-pattern '^\s*};$' \
                --exclude-lines-by-pattern '^.*GCOVR_EXCL_LINE.*$' \
                --exclude-unreachable-branches \
                --exclude-throw-branches \
                -j 2 \
                --xml \
                --output ${{ github.workspace }}/build/coverage_report.xml

      - name: Submit coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/build/coverage_report.xml
          root_dir: ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}
